services:
  mongo:
    image: mongodb/mongodb-community-server
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: monclero/techcrush-backend:v1
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/techcrush
      - JWT_SECRET=group1-techcrush.
    depends_on:
      - mongo
   

  frontend:
    image: monclero/techcrush-frontend:v1
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo-data: