name: CI/CD Pipeline - Build, Push, Deploy

on:
 push:
  branches:
   - MONCLERO # Run file only when pushed to main

jobs:
 build-and-deploy:
  runs-on: ubuntu-latest

  steps:
   #---
   # Step 1: Checkout code
   #---
   - name: Checkout repo
     uses: actions/checkout@v4

  #  - name: Set up QEMU
  #    uses: docker/setup-qemu-action@v2

  #  - name: Set up Docker Buildx
  #    uses: docker/setup-buildx-action@v2

  #  - name: Login to Docker Hub
  #    uses: docker/login-action@v2
  #    with:
  #     username: ${{ secrets.DOCKERHUB_USERNAME }}
  #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

  #  - name: Build and push frontend
  #    uses: docker/build-push-action@v4
  #    with:
  #     context: ./frontend 
  #     push: true
  #     tags: | 
  #       monclero/techcrush-frontend:v1.0
  #       monclero/techcrush-frontend:${{ github.sha }}

  #  - name: Build and push backend
  #    uses: docker/build-push-action@v4
  #    with:
  #     context: ./frontend 
  #     push: true
  #     tags: | 
  #       monclero/techcrush-frontend:v1.0
  #       monclero/techcrush-frontend:${{ github.sha }}


  #  #---
  #  # Step 7: Echo Images Pushed 
  #  #---
  #  - name: Summary
  #    run: |
  #       echo "### Docker Images Pushed" >> $GITHUB_STEP_SUMMARY
  #       echo "- \`lexyuko/tech-crush-group-1-backend:${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
  #       echo "- \`francesehinor/tech-crush-group-1-frontend:${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
   
   #---
   # Step 8: Deploy on Azure VM via SSH
   #---
   - name: Deploy on Azure VM
     uses: D3rHase/ssh-command-action@latest
     with:
       host: ${{ vars.VM_HOST }}
       user: ${{ vars.VM_USER }}
       private_key: ${{ vars.VM_SSH_KEY }}
       command: |
            mkdir -p docker-project
            cd ~/docker-project || git clone "git clone link" docker-project
            cd docker-project
            git pull origin main
            cd ~/
            sudo docker compose down
            sudo docker pull "backend link"
            sudo docker pull "frontend link"
            sudo docker compose up -d --build  
            
