name: CI/CD Pipeline - Build, Push, Deploy

on:
 push:
  branches:
   - MONCLERO # Run file only when pushed to main

jobs:
 build-and-deploy:
  runs-on: ubuntu-latest

  steps:
   #---
   # Step 1: Checkout code
   #---
   - name: Checkout repo
     uses: actions/checkout@v4

   #---
   # Step 2: Login to Docker Hub
   #---
   - name: Login to Docker Hub
     uses: docker/login-action@v2
     with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

   #---
   # Step 3: Build on Runner & Push Frontend Image to DockerHub
   #---
   - name: Build and Push Frontend
     uses: docker/build-push-action@v4
     with:
      context: ./frontend
      push: true
      tags: | 
         monclero/techcrush-frontend:v2
         monclero/techcrush-frontend:${{ github.sha }}

    #---
    # Step 4: Build on Runner & Push Backend Image To DockerHub
   - name: Build and Push Backend
     uses: docker/build-push-action@v4
     with:
      context: ./Backend
      push: true
      tags: | 
         monclero/techcrush-backend:v2
         monclero/techcrush-backend:${{ github.sha }}

    #---
    # Step 7: Echo Images Pushed 
    #---
   - name: Summary
     run: |
         echo "### Docker Images Pushed" >> $GITHUB_STEP_SUMMARY
         echo "- \`monclero/techcrush-backend:v1${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
         echo "- \`monclero/techcrush-frontend:v1${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
   
   #---
   # Step 8: Deploy on Azure VM via SSH
   #---
   - name: Deploy on Azure VM
     uses: D3rHase/ssh-command-action@latest
     with:
       host: ${{ secrets.VM_HOST }}
       user: ${{ secrets.VM_USER }}
       private_key: ${{ secrets.VM_SSH_KEY }}
       command: |
          # Clone repo if it does not exist
          if [ ! -d ~/tech-crush-1/.git ]; then
            git clone git@github.com:lexyuko/Tech_Crush-1.git ~/tech-crush-1
          fi

          # Pull latest
          cd ~/docker-project
          git pull MONCLERO

          # Pull Docker Images and Restart services
          docker compose pull
          docker compose up -d
          